require("dotenv").config();
const express = require("express");
const connectDB = require("./config/db");
const app = express();
app.use(express.json());
connectDB();
app.use("/expenses", require("./routes/expenses"));
app.use("/", require("./routes/settlements"));
app.get("/", (req, res) => res.send("Split App API Running"));
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));